name: Hello World Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:  # This allows for manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Hello World
        run: echo "Hello, World!"